/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./mock";
export type { mock };
export type { IBalanceOf } from "./IBalanceOf";
export type { WrappedToken } from "./WrappedToken";
export type { YourContract } from "./YourContract";
export type { YourNFT } from "./YourNFT";
